name: commercial_district
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - altair=6.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - backports.zstd=1.3.0=py312h06d0912_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cachetools=6.2.6=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=23.0.0=h7d27241_1_cuda
  - libarrow-acero=23.0.0=h7d8d6a5_1_cuda
  - libarrow-compute=23.0.0=h2db994a_1_cuda
  - libarrow-dataset=23.0.0=h7d8d6a5_1_cuda
  - libarrow-substrait=23.0.0=hf865cc0_1_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libgomp=15.2.0=h8ee18e1_17
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - liblzma-devel=5.8.2=hfd05255_0
  - libparquet=23.0.0=h7051d1f_1_cuda
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.3=hb980946_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py312h05f76fc_0
  - mkl=2025.3.0=hac47afa_455
  - narwhals=2.16.0=pyhcf101f3_0
  - numpy=2.4.2=py312ha72d056_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=hbd3206f_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py312hc128f0a_2
  - pillow=12.1.0=py312h31f0997_0
  - pip=26.0.1=pyh8b19718_0
  - protobuf=6.31.1=py312hcb3287e_2
  - pthread-stubs=0.4=h0e40799_1002
  - pyarrow-core=23.0.0=py312h6654431_0_cuda
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.4=h889d299_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h05f76fc_1
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rpds-py=0.30.0=py312hdabe01f_0
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - streamlit=1.54.0=pyhd8ed1ab_0
  - tbb=2022.3.0=h3155e25_2
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.13=h6ed50ae_3
  - toml=0.10.2=pyhcf101f3_3
  - tornado=6.5.4=py312he06e257_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - watchdog=6.0.0=py312h2e8e312_2
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.8.2=hb6c8415_0
  - xz-tools=5.8.2=hfd05255_0
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.3=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - pyarrow==23.0.0
prefix: C:\Users\osh54\anaconda3\envs\commercial_district
